"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gps_command(object):
    __slots__ = ["x", "y", "p", "q"]

    __typenames__ = ["double", "double", "double", "double"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.x = 0.0
        self.y = 0.0
        self.p = 0.0
        self.q = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(gps_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dddd", self.x, self.y, self.p, self.q))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps_command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gps_command()
        self.x, self.y, self.p, self.q = struct.unpack(">dddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gps_command in parents: return 0
        tmphash = (0x9b1dee9dfc9cc421) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gps_command._packed_fingerprint is None:
            gps_command._packed_fingerprint = struct.pack(">Q", gps_command._get_hash_recursive([]))
        return gps_command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

