"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class action_command(object):
    __slots__ = ["leftspeed", "rightspeed"]

    __typenames__ = ["int16_t", "int16_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.leftspeed = 0
        self.rightspeed = 0

    def encode(self):
        buf = BytesIO()
        buf.write(action_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hh", self.leftspeed, self.rightspeed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != action_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return action_command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = action_command()
        self.leftspeed, self.rightspeed = struct.unpack(">hh", buf.read(4))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if action_command in parents: return 0
        tmphash = (0xb2e9f13f77a2fc60) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if action_command._packed_fingerprint is None:
            action_command._packed_fingerprint = struct.pack(">Q", action_command._get_hash_recursive([]))
        return action_command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

