"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class collision_robots(object):
    __slots__ = ["robots_len", "collision_array"]

    __typenames__ = ["int16_t", "double"]

    __dimensions__ = [None, ["robots_len", 3]]

    def __init__(self):
        self.robots_len = 0
        self.collision_array = []

    def encode(self):
        buf = BytesIO()
        buf.write(collision_robots._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.robots_len))
        for i0 in range(self.robots_len):
            buf.write(struct.pack('>3d', *self.collision_array[i0][:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != collision_robots._get_packed_fingerprint():
            raise ValueError("Decode error")
        return collision_robots._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = collision_robots()
        self.robots_len = struct.unpack(">h", buf.read(2))[0]
        self.collision_array = []
        for i0 in range(self.robots_len):
            self.collision_array.append(struct.unpack('>3d', buf.read(24)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if collision_robots in parents: return 0
        tmphash = (0x3205cb299e9b4a3f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if collision_robots._packed_fingerprint is None:
            collision_robots._packed_fingerprint = struct.pack(">Q", collision_robots._get_hash_recursive([]))
        return collision_robots._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

